const pokemon = [
  {
    id: '1',
    name: 'Bulbasaur',
    type: 'grass/poison',
    hp: 49,
    attack: 49,
    defense: 49,
    url: 'https://img.pokemondb.net/artwork/large/bulbasaur.jpg',
  },
  {
    id: '2',
    name: 'Dratini',
    type: 'dragon',
    hp: 41,
    attack: 64,
    defense: 45,
    url: 'https://img.pokemondb.net/artwork/large/dratini.jpg',
  },
  {
    id: '3',
    name: 'Charmander',
    type: 'fire',
    hp: 39,
    attack: 52,
    defense: 43,
    url: 'https://img.pokemondb.net/artwork/large/charmander.jpg',
  },
  {
    id: '4',
    name: 'Squirtle',
    type: 'water',
    hp: 44,
    attack: 48,
    defense: 65,
    url: 'https://img.pokemondb.net/artwork/large/squirtle.jpg',
  },
  {
    id: '5',
    name: 'Rattata',
    type: 'normal',
    hp: 30,
    attack: 56,
    defense: 35,
    url: 'https://img.pokemondb.net/artwork/large/rattata.jpg',
  },
  {
    id: '6',
    name: 'Sandshrew',
    type: 'ground',
    hp: 50,
    attack: 75,
    defense: 85,
    url: 'https://img.pokemondb.net/artwork/large/sandshrew.jpg',
  },
  {
    id: '7',
    name: 'Abra',
    type: 'psychic',
    hp: 25,
    attack: 20,
    defense: 15,
    url: 'https://img.pokemondb.net/artwork/large/abra.jpg',
  },
  {
    id: '8',
    name: 'Diglett',
    type: 'ground',
    hp: 10,
    attack: 55,
    defense: 25,
    url: 'https://img.pokemondb.net/artwork/large/diglett.jpg',
  },
  {
    id: '9',
    name: 'Mankey',
    type: 'fighting',
    hp: 40,
    attack: 80,
    defense: 35,
    url: 'https://img.pokemondb.net/artwork/large/mankey.jpg',
  },
  {
    id: '10',
    name: 'Machop',
    type: 'fighting',
    hp: 70,
    attack: 80,
    defense: 50,
    url: 'https://img.pokemondb.net/artwork/large/machop.jpg',
  },
  {
    id: '11',
    name: 'Eevee',
    type: 'normal',
    hp: 55,
    attack: 55,
    defense: 50,
    url: 'https://img.pokemondb.net/artwork/large/eevee.jpg',
  },
  {
    id: '12',
    name: 'Pidgey',
    type: 'flying',
    hp: 40,
    attack: 45,
    defense: 40,
    url: 'https://img.pokemondb.net/artwork/large/pidgey.jpg',
  },
];

module.exports = { pokemon };
